[package]
name = "simd-json-derive"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd-json-derive-int = {path = "./simd-json-derive-int"}
value-trait = "0.1"
itoa = "0.4"
ryu = "1"
