[package]
name = "simd-json-derive"
version = "0.1.14-alpha.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "derives for simd-json"
documentation = "https://docs.rs/simd-json-derive"
readme = "README.md"
homepage = "https://docs.rs/simd-json-derive"
repository = "https://github.com/simd-lite/simd-json-derive/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd-json-derive-int = { path = "./simd-json-derive-int", version = "0.1.4" }
value-trait = "0.1"
itoa = "0.4"
ryu = "1"
chrono = {version = "0.4", optional = true}
simd-json = "0.3"

[dev-dependencies]
serde_json = "1"
serde = "1"

[features]
default = ["impl-chrono"]
impl-chrono = ["chrono"]
