name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        rustflags:
          - '-C target-cpu=native'
        features:
          - ''
          - '--features 128bit'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo build ${{ matrix.features }}
    - name: Run tests
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo test ${{ matrix.features }}
